### ISSUE TITLE
An error occurred: gnutls_handshake() failed: Handshake failed.

### ISSUE THREAD

**Issue by tarlepp** [sensiolabs/security-checker#100]
Just noticed that TravisCI gives that error. Full log https://travis-ci.org/tarlepp/symfony-flex-backend/jobs/294956683

**Comment by lyrixx** [comment]
I have the same issue :(

Do someone know how to fix that ?

**Comment by JeromeGill** [comment]
I feel like disabling the security checker in CI might defeat the point somewhat.

**Comment by pchelk1n** [comment]
I have the same issue

**Comment by lyrixx** [comment]
Hello @tucksaun ; Maybe you have an idea here

**Comment by tucksaun** [comment]
Still the same as https://github.com/sensiolabs/security-checker/pull/77#issuecomment-290733113 I guess as the original travis-ci issue is still opened.
My bet is that they didn't progress on this.

So two things to do:
- ~do some lobbying on https://github.com/travis-ci/travis-ci/issues/6339 to get them to fix it~ oh actually, helping them to fix it could be better: https://github.com/travis-ci/travis-ci/issues/6339#issuecomment-355158125, unfortunately, I'm kind of too busy right now to do it myself
- use the HTTP-only endpoint in the meantime.

**Comment by fabpot** [comment]
Closing as there is apparently nothing we can do here.
