### ISSUE TITLE
security-checker.phar cannot be downloaded over HTTPS

### ISSUE THREAD

**Issue by willemstuursma** [sensiolabs/security-checker#101]
It would be great if I could automatically download this tool over HTTPS instead of HTTP.

**Comment by kaystrobach** [comment]
how about integrating it into phive? -> phar.io

**Comment by halfer** [comment]
Duplicates this issue? https://github.com/sensiolabs/security-checker/issues/68

**Comment by kaystrobach** [comment]
Sure close it please

**Comment by halfer** [comment]
Hi @fabpot, would you close this? Thanks.
