### ISSUE TITLE
Phar not working on PHP 5.6

### ISSUE THREAD

**Issue by OndraM** [sensiolabs/security-checker#103]
Hi, starting today our jenkins jobs on PHP 5.6.30 which downloads and runs current phar stopped working.

```
$ wget http://get.sensiolabs.org/security-checker.phar
$ chmod a+x security-checker.phar
$ ./security-checker.phar security:check composer.lock
PHP Fatal error:  Default value for parameters with a class type hint can only be NULL in phar:///var/lib/jenkins/jobs/.../workspace/security-checker.phar/vendor/symfony/console/Application.php on line 83
PHP Stack trace:
PHP   1. {main}() /var/lib/jenkins/jobs/.../workspace/security-checker.phar:0
PHP   2. require() /var/lib/jenkins/jobs/.../workspace/security-checker.phar:10
PHP   3. spl_autoload_call() /var/lib/jenkins/jobs/.../workspace/security-checker.phar:29
PHP   4. Composer\Autoload\ClassLoader->loadClass() /var/lib/jenkins/jobs/.../workspace/security-checker.phar:29
PHP   5. Composer\Autoload\includeFile() phar:///var/lib/jenkins/jobs/.../workspace/security-checker.phar/vendor/composer/ClassLoader.php:322
```

Is the phar still supposed to work on PHP 5.6? Something changed in last ~24 hours?

**Comment by fabpot** [comment]
That's because of 387b6a3b723ba35588b33d5f8d14e28ed608bd30. As we are allowing Symfony 4, and because Symfony 4 is now stable, my commit yesterday trigerred a new phar and it used Symfony 4.0 stable (which is not compatible with PHP 5.6). Not sure what to do here.

**Comment by OndraM** [comment]
Wouldn't be an option some kind of versioning via the URL?

http://get.sensiolabs.org/security-checker.phar -> latest
http://get.sensiolabs.org/security-checker-4.1.6.phar -> specific version
http://get.sensiolabs.org/security-checker.phar?v=4.1.6. -> or like this?
http://get.sensiolabs.org/security-checker-php56.phar -> or maybe version compatible with php 5.6?
http://get.sensiolabs.org/security-checker-legacy.phar -> or something like this?

**Comment by xarem** [comment]
@fabpot a versioning strategy like the GitLab Runner would be nice:

https://docs.gitlab.com/runner/install/bleeding-edge.html#download-any-other-tagged-release

Maybe you can automatically add a phar to the GitHub releases via box?

**Comment by tucksaun** [comment]
Actually, URLs like http://get.sensiolabs.org/security-checker-v4.1.6.phar are already available :)

**Comment by adek23** [comment]
Moreover, IMHO composer.json should have specified minimum php version to run.

**Comment by theofidry** [comment]
@fabpot what is the PHP target here? 5.6+ or 7.1+?
