### ISSUE TITLE
Breaks on php 7

### ISSUE THREAD

**Issue by coreorm** [sensiolabs/security-checker#104]
See error below:

$  php ../security-checker.phar security:check composer.lock
PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in phar://security-checker.phar/vendor/symfony/console/Output/Output.php on line 40

**Comment by fabpot** [comment]
It means that you are not using PHP 7, but probably an earlier version.

**Comment by coreorm** [comment]
yeah it's 7.0.23

**Comment by xabbuh** [comment]
The phar seems to be built using PHP 7.1 (see also #103).
