### ISSUE TITLE
Likely need an addition for public Propel vulnerability 

### ISSUE THREAD

**Issue by halfer** [sensiolabs/security-checker#106]
I don't have authority from the Propel project to raise a PR, but I don't think this should be allowed to drop off the radar. A serious SQL injection vulnerability was published to the public issues list on the Propel project, which (it is said) affects all prior versions.

https://github.com/propelorm/Propel2/issues/1463

I have asked the maintainer as to whether a PR should be raised here, but the report was closed shortly afterwards. I don't know if that means it is in hand, or it is not.

If I can be assistance in raising a PR I am happy to help, but of course I'd like to do so in conjunction with the Propel team if possible. To complicate matters, the project appears to have somewhat stalled over the last few years, so the problem may just be a lack of hands wanting to do active maintenance.

Marc, can you comment here?

**Comment by fabpot** [comment]
Anyone can submit a PR for adding new vulnerability. This can be done easily here: FriendsOfPHP/security-advisories. By the way, no need to get approval from the project itself.
