### ISSUE TITLE
Improve `--offline` mode

### ISSUE THREAD

**Issue by evilebottnawi** [sensiolabs/security-checker#109]
Example offline mode: https://github.com/nodesecurity/nsp

In short:
1. Create command what downloads `advisories` in local file, example `php-advisories.json`
2. If you use `--offline` flag look into this file without internet connection.

Why?
It is allow run CI integration tests without internet connection and don't break build when internet connection falls. We just run another task to upgrade `php-advisories.json` each `24h` (just example).

**Comment by fabpot** [comment]
That's out of the scope of this project as there would be no code in common between the online and the offline mode.

**Comment by evilebottnawi** [comment]
@fabpot very bad :disappointed:

**Comment by fabpot** [comment]
@evilebottnawi How is it bad? Anybody can create such a project that would work offline. Why would I be the one implementing that?

**Comment by evilebottnawi** [comment]
@fabpot It would be more convenient to implement this here than to do in another repository, it's not too difficult

**Comment by evilebottnawi** [comment]
@fabpot due with attempts RNK blocked `Telegram` in Russian we are experiencing difficulties with CI (they blocked many amazon/google/other ip networks) :disappointed: `security.sensiolabs.org` now is blocked in Russian :disappointed: Maybe we can implement offline mode?

**Comment by theofidry** [comment]
An offline mode gives a false sense of security and introduce the issue of having to take care of updating the advisory periodically.

Instead maybe a service like http://security.symfony.com/ would be more adapted

**Comment by evilebottnawi** [comment]
@theofidry we have many repos and did not plan to move to paid solutions, `nsp` for `nodejs` is same tools and support offline mode. It will be easy implement https://github.com/nodesecurity/nsp#offline-mode

**Comment by evilebottnawi** [comment]
We cache `advisories.json` in CI and try  3 times run `nsp gather` (we always use zero code for this to avoid network or other problem) when run `nsp check --offline`

**Comment by theofidry** [comment]
Then you can try to implement this on a fork and if the implementation is simple enough you may request for it to be merged back here.

Also an alternative could be to try https://github.com/Roave/SecurityAdvisories which uses this project as a base but tackles it differently
