### ISSUE TITLE
security-checker error code 255 on vendor/symfony/console/Application.php on line 83

### ISSUE THREAD

**Issue by ecataranciuc** [sensiolabs/security-checker#113]
On Symfony 4.0.8 (Flex) security-checker throws:
```
Script security-checker security:check returned with error code 255
!!  PHP Fatal error:  Default value for parameters with a class type hint can only be NULL in /var/www/vhosts/dev.harubik.com/httpdocs/vendor/symfony/console/Application.php on line 83
```
Seems like a bug. The setup is pretty vanilla. Basically I render templates without custom controllers.

**Comment by nicolas-grekas** [comment]
Symfony v4 requires PHP 7.1. This error happens because you're using a lower version I suppose.

**Comment by ecataranciuc** [comment]
I apologize, I forgot to mention that I use PHP 7.2.

**Comment by nicolas-grekas** [comment]
But as you can see, this error makes no sense:
https://github.com/symfony/symfony/blob/4.0/src/Symfony/Component/Console/Application.php#L83
Except if this is run with PHP5. You should double check.

**Comment by ecataranciuc** [comment]
The issue is encountered on a Plesk machine.
```
bash-4.2$ /opt/plesk/php/7.2/bin/php -v
PHP 7.2.4 (cli) (built: Apr  4 2018 10:22:01) ( NTS )
```
```
bash-4.2$ /opt/plesk/php/7.2/bin/php /usr/lib64/plesk-9.0/composer.phar install --no-dev --optimize-autoloader
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 0 installs, 0 updates, 7 removals
  - Removing symfony/web-server-bundle (v4.0.8)
  - Removing symfony/web-profiler-bundle (v4.0.8)
  - Removing symfony/var-dumper (v4.0.8)
  - Removing symfony/stopwatch (v4.0.8)
  - Removing symfony/profiler-pack (v1.0.3)
  - Removing symfony/process (v4.0.8)
  - Removing symfony/polyfill-php72 (v1.7.0)
Generating optimized autoload files
Executing script cache:clear [OK]
Executing script assets:install --symlink --relative public [OK]
Executing script security-checker security:check [KO]
 [KO]
Script security-checker security:check returned with error code 255
!!  PHP Fatal error:  Default value for parameters with a class type hint can only be NULL in /path/to/project/vendor/symfony/console/Application.php on line 83
!!
```

**Comment by ecataranciuc** [comment]
I agree it doesn't make sense. That's why I reported it as a bug.

**Comment by ecataranciuc** [comment]
Maybe I am doing something wrong:
bash-4.2$ /opt/plesk/php/7.2/bin/php bin/console security
2018-04-14T22:10:34+00:00 [error] Error thrown while running command "security". Message: "Command "security" is not defined."

**Comment by nicolas-grekas** [comment]
The command is `security:check`, see README:
https://github.com/sensiolabs/security-checker

**Comment by ecataranciuc** [comment]
Must be related to OS environment. It works fine on my dev machine. I will update this once I figure it out.
