### ISSUE TITLE
Introduce semi-quiet option (only output findings)

### ISSUE THREAD

**Issue by hannob** [sensiolabs/security-checker#114]
Right now security-checker has a "quiet" option that won't output anything and various verbosity options.

However what it doesn't have and what I'd find very useful for automation is a way to say "Please tell me all vulnerable version findings, but don't output anything if everything's all right". E.g. one could have a cronjob that regularly checks software where cron will send an email if output is generated.

**Comment by fabpot** [comment]
I would recommend to fix the way emails are sent instead. Output does not mean that there is something wrong. Read more at https://github.com/symfonycorp/croncape
