### ISSUE TITLE
Add ability to pass "-" / stdin

### ISSUE THREAD

**Issue by hannob** [sensiolabs/security-checker#115]
Right now security-checker can only scan the composer.lock file in the current directory.

This is quite inflexible, i.e.:
1. One can't just pass a path to check.
2. It's not possible to pipe in info, e.g. curl https://example.com/composer.lock | security-checker [...] --infile -

Can you add an option to allow passing an input filename?

**Comment by xabbuh** [comment]
`security-checker path/to/composer.lock` should already work

**Comment by hannob** [comment]
Oh sorry, you're right, passing a path works. Should probably be indicated in the help screen though.

However still piping something over via stdin doesn't work:
$ security-checker.phar security:check -

always outputs:

  Lock file does not exist.

**Comment by fabpot** [comment]
@hannob Would you like to create a pull request (on the 4.1 branch) to add support for stdin?

As for the help text, it's documented:

```
./security-checker sec:check --help                                                                                                                                      4.1 ◼
Usage:
  security:check [options] [--] [<lockfile>]

Arguments:
  lockfile                   The path to the composer.lock file [default: "composer.lock"]

Options:
      --format=FORMAT        The output format [default: "text"]
      --end-point=END-POINT  The security checker server URL
      --timeout=TIMEOUT      The HTTP timeout in seconds
  -h, --help                 Display this help message
  -q, --quiet                Do not output any message
  -V, --version              Display this application version
      --ansi                 Force ANSI output
      --no-ansi              Disable ANSI output
  -n, --no-interaction       Do not ask any interactive question
  -v|vv|vvv, --verbose       Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
  The security:check command looks for security issues in the
  project dependencies:

  php ./security-checker security:check

  You can also pass the path to a composer.lock file as an argument:

  php ./security-checker security:check /path/to/composer.lock

  By default, the command displays the result in plain text, but you can also
  configure it to output JSON instead by using the --format option:

  php ./security-checker security:check /path/to/composer.lock --format=json
```

**Comment by fabpot** [comment]
Closing as this project is not maintained anymore. See https://github.com/fabpot/local-php-security-checker for an open-source software that does the same locally (without any API calls).
