### ISSUE TITLE
Versioned URL

### ISSUE THREAD

**Issue by ad-si** [sensiolabs/security-checker#117]
Is there a versioned URL a la `http://get.sensiolabs.org/security-checker-4.1.8.phar` available?

**Comment by tucksaun** [comment]
Yes, the whole tag is used so you need to add `v` in the version number, for example `http://get.sensiolabs.org/security-checker-v4.1.8.phar`

**Comment by ad-si** [comment]
Ah, I almost guessed it correctly. 😅
Thanks, cool, that it exists! 😁

Maybe you should mention it in the reamde?

**Comment by ad-si** [comment]
Oh and btw:
Shouldn't `security-checker --version` print the whole version number and not just `SensioLabs Security Checker 4`?

**Comment by fabpot** [comment]
Closing now as version 4 is not maintained anymore.
