### ISSUE TITLE
Allow to add exceptions

### ISSUE THREAD

**Issue by mdio** [sensiolabs/security-checker#119]
It would help our workflow if we could add exceptions for specific CVE numbers.
The node security platform [allows for this](https://github.com/nodesecurity/nsp#exceptions) using an .nsprc file.

I recognize that this has the potential to shoot yourself in the foot but on the other hand I wouldn't expect people who go to great lengths to integrate that into their process to use this to just whitelist every CVE they encounter.

On the other hand for us it's very annoying when our Jenkins pipeline fails with an error again and again (it runs after every commit to master which is quite often).
So the ability to mute a specfic CVE (and start working on upgrading) would be very helpful.

Muting the tool completely to achieve that would leave us blind for new CVE's coming in, so that would be problematic.

**Comment by OwnerOfThisIsle** [comment]
I also would like that.
Use case: Our process will include a step before deploy where it the risk manager has to evaluate CVE's and to decide to update at once or later.
In the second case we would need a possibility to change the build pipeline to allow the build to be green, despite the (evaluated) CVEs..

**Comment by fabpot** [comment]
Closing for the same reasons explained in #124

**Comment by InstanceOfMichael** [comment]
That's lame, this is the only security-checker I'm using that doesn't have a whitelist feature for the valid use cases mentioned in the locked issue.
