### ISSUE TITLE
add option to ouput result as junit file

### ISSUE THREAD

**Issue by kaystrobach** [sensiolabs/security-checker#121]
More and more people are used to use gitlab an other CI tools, junit integration would help a lot with that kind of integrations

**Comment by kaystrobach** [comment]
getting more and more important ... 

https://docs.gitlab.com/ee/ci/junit_test_reports.html#how-it-works

**Comment by jamessampford** [comment]
This would be a handy addition to workflows

**Comment by fabpot** [comment]
Closing as this project is not maintained anymore. See https://github.com/fabpot/local-php-security-checker for an open-source software that does the same locally (without any API calls).
