### ISSUE TITLE
How to convince your boss?

### ISSUE THREAD

**Issue by Quix0r** [sensiolabs/security-checker#122]
We use Laravel 5.3.31 here at work. How can I convince my boss to upgrade? When I just show the report, he will ask me if that is my current task (this is an irresponsibility, of course) and I'm being told (I tried it before with an other application we write, no avail) that the sponsor is not paying such things (again irresponsibility). We have no employee organization (no representative) where I could go and complain.

So what hard reasons should I bring up?

**Comment by maxhelias** [comment]
You do not have to convince, security is part of your tasks. Moreover, you should use a LTS like 5.5 which has new features, better performance and better security. These are just things that anyone wants.

And if he does not want to hear you, the only thing you can do is resign.

One last thing, for this kind of question you will have more results on forums or on the Symfony slack

**Comment by Quix0r** [comment]
I think the same way as you, thank you! :-) But sadly here you are not given enough time to handle such things which is bad news. So I really have to consider now.

I wait for more ideas (no legal things here, of course, like setting ultimatums or such).

**Comment by maxhelias** [comment]
I do not know where you are, but in France and Europe, there are laws to regulate the use and security of personal information such as the CNIL or the GPDR.

If this is your case, you have the legal and econimic argument

**Comment by fridzema** [comment]
@Quix0r do your boss have the knowledge to examine this? 
I guess your boss hired you because you can...
Maybe you must let him sign a contract that he is aware of the risks and agreed to take the risks. 
I it goes wrong later all the fingers are pointed to you...
