### ISSUE TITLE
The web service failed for an unknown reason (HTTP 429).

### ISSUE THREAD

**Issue by gemal** [sensiolabs/security-checker#126]
php Vendor\sensiolabs\security-checker\security-checker security:check composer.lock

`The web service failed for an unknown reason (HTTP 429).`

anything I'm doing wrong here or?

```
php Vendor\sensiolabs\security-checker\security-checker security:check --version
SensioLabs Security Checker 5.0
```

**Comment by fabpot** [comment]
There was an issue with the rate limiter. This has been fixed now.
