### ISSUE TITLE
lock file is not valid (no packages and no dev packages)

### ISSUE THREAD

**Issue by EAnushan** [sensiolabs/security-checker#131]
Why do we return an error when a package has no dependencies? We run the security checker during our CI builds, and any bottom level packages that have no dependencies never pass because they have no dependencies.

Is there a flag to suppress this error? Does it make sense to treat empty lock files as erroneous?

**Comment by fabpot** [comment]
Can you give me such an empty composer.lock?

**Comment by fabpot** [comment]
Allowed now.
