### ISSUE TITLE
Add security-checker to PHIVE

### ISSUE THREAD

**Issue by shochdoerfer** [sensiolabs/security-checker#132]
I'd love to be able to install security-checker via [PHIVE](https://phar.io).

Steps needed to enable PHIVE support:
1. Deploy a phive.xml file to your webserver, see [here](https://github.com/phar-io/phar.io/blob/master/data/repository.xsd) for the XSD or [here](https://github.com/sebastianbergmann/phar-site-generator) for a project generating such a file
2. Add the phive.xml url to list of [PHIVE repositories](https://github.com/phar-io/phar.io/blob/master/data/repositories.xml)

**Comment by theofidry** [comment]
@shochdoerfer note that you can already do it:

```
$ phive install sensiolabs/security-checker --force-accept-unsigned
```

**Comment by shochdoerfer** [comment]
sure, but want to do it the cool way :P

**Comment by fabpot** [comment]
I'm closing this issue as I think using the Symfony CLI is better now. #144
