### ISSUE TITLE
Rate limit questions

### ISSUE THREAD

**Issue by marcovtwout** [sensiolabs/security-checker#133]
Since last week we've been getting HTTP 429 responses (rate limit exceeded) when quering the API on https://security.sensiolabs.org/check_lock. I couldn't find any documented policy about the rate limit. What is the recommended way to handle this: how many requests are typically allowed and how long should I back off when the rate limit is reached?

**Comment by davejamesmiller** [comment]
I'd like to know the same.

The headers say:

```
Ratelimit-Limit: 1800
Ratelimit-Remaining: 10
```

However, the remaining count seems to go down by 4 for each check, not 1. I tested on both a composer.lock with a single dependency and one with 20+ dependencies, so I don't think it's based on the number of packages checked.

Based on watching it for a few minutes, it looks like it increases by approx. 1 per minute, so it would take 30 hours to fully replenish. So that would be 450 checks per 30 hours, or average 360 per day.

But I could be wrong here - I don't think we're doing that many checks yet still hit the limit. (Unless there's a bug somewhere in my script!)

(On a related note - I'd happily run the check locally against https://github.com/FriendsOfPHP/security-advisories, to avoid hitting any API, but I can't find any way to do that other than writing it myself...)

**Comment by scaytrase** [comment]
We've started hitting rate limit today too

**Comment by henneboele** [comment]
Same for us. Also querying the API for all our apps during build processes.
A documentation about that would be nice.

**Comment by marcovtwout** [comment]
Increasing by one per minute seems about accurate. But after one day of waiting, the rate limit-remaining is still at 10. A request makes it go down by 4. So currently it seems I can do only 1 request per 4 minutes, that can't be intended?

**Comment by fabpot** [comment]
First of all, you need to make sure you are using the latest version of the CLI (version 5), that's the only version that will not burn your credits too fast.

**Comment by marcovtwout** [comment]
@fabpot I'm currently not using the CLI but simply using CURL requests fired at https://security.sensiolabs.org/check_lock - is that approach not valid anymore?

**Comment by xabbuh** [comment]
The new endpoint is https://security.symfony.com/check_lock.

**Comment by marcovtwout** [comment]
After waiting one week, the credits remaining is now at 24. When trying the new endpoint, it still goes down by 3-4 per request.

**Comment by BackEndTea** [comment]
> The "new" endpoint is https://security.symfony.com/check_lock (see also #94).

@xabbuh Is the old endpoint going to 'disappear' any time soon?

**Comment by fabpot** [comment]
@BackEndTea The official answer is "YES". But the reality is that there is still too much traffic on the old domain name to shut it down.

**Comment by BackEndTea** [comment]
Is there any kind of ETA on that?
I'm in the process of updating some projects to 5.0 and i'd like to know what timeframe i have for that

**Comment by fabpot** [comment]
ETA was end of last November :) I'd like people to plan the upgrade. End of January would be great if possible. And if I need to give a hard stop, I would say June 2019 at the latest.

**Comment by BackEndTea** [comment]
Thanks for the heads up, i'll be sure to get updating

**Comment by marcovtwout** [comment]
@fabpot I think this should be reopened for one remaining issue: Can you document somewhere that the rate limit exists, and preferably how the client should handle it?

(maybe adding a few lines to this repo's README would suffice)

**Comment by marcovtwout** [comment]
(in the meantime, for anyone googling the error message without knowledge of the rate limit:)

I've updated to the latest CLI version using the SecurityChecker class directly in code. When the rate limit is reached, it ends in `SensioLabs\Security\Exception\HttpException: The web service failed for an unknown reason (HTTP 429)`.

**Comment by royduin** [comment]
Anyone knows the rate limit? How many requests are allowed per hour or day?

**Comment by marcovtwout** [comment]
It looks like about one request per minute is the minimum to avoid hitting the rate limiter eventually.
