### ISSUE TITLE
file_get_contents() doesn't consider proxy

### ISSUE THREAD

**Issue by edditor** [sensiolabs/security-checker#134]
After updating from 4.18. to 5.0.1 (which includes the removal of cURL support) our CI pipeline which is behind a proxy fails with a timeout.
`An error occurred: file_get_contents(https://security.symfony.com/check_lock): failed to open stream: Connection timed out.  `

We are setting the HTTP_PROXY/HTTPS_PROXY environment vars which works very well with the cURL crawler. The proxy is not considered by the stream_context_create() call.

**Comment by fabpot** [comment]
Closing as a duplicate for #19
