### ISSUE TITLE
Json integer read error

### ISSUE THREAD

**Issue by XSlicer** [sensiolabs/security-checker#139]
Whenever a composer.lock contains an integer instead of a string, as example a package version is just '7' and not '7.1.0', composer writes this as an integer in the composer.lock instead of a string.

Consequently security-checker will consider this json file to be incorrect:
"lock file is not valid JSON (not a composer.lock file?)"

Replacing the "version": 7 with "version": "7" will work. I assume there is an issue in not expecting integers in the json file.

(This issue came up with wpackagist-plugin/404page)

**Comment by fabpot** [comment]
Can you give us a simple `composer.lock` that fails?

**Comment by fabpot** [comment]
Fixed now

**Comment by XSlicer** [comment]
Thanks, apologies I couldn't produce an example this weekend.
