### ISSUE TITLE
Request with HTTP/2 fails due to lowercase headers

### ISSUE THREAD

**Issue by bytehead** [sensiolabs/security-checker#145]
Hi

Somehow if I use `php bin/console security:check` HTTP/2 is used (I did not get the reason for that) and this is the (dumped) response: 

```
"""
HTTP/2 200 \r\n
content-type: text/plain; charset=utf-8\r\n
date: Wed, 19 Dec 2018 07:17:45 GMT\r\n
ratelimit-limit: 1800\r\n
ratelimit-remaining: 17\r\n
strict-transport-security: max-age=0\r\n
vary: Origin\r\n
x-alerts: 0\r\n
x-correlation-id: mw45yo2ggb7p6u6nxgxtitea\r\n
x-debug-info: eyJyZXRyaWVzIjowfQ==\r\n
x-symfony-cluster: nqknp632nz4yy-master-7rqtwti\r\n
x-symfony-processor: 7fesyyklho5tj7nu34ygwytqgu\r\n
x-symfony-router: xhar4zod6hbhdqoj4qdve674g4\r\n
content-length: 2\r\n
\r\n
"""
"{}"
```

The check will fail due to this line: https://github.com/sensiolabs/security-checker/blob/master/SensioLabs/Security/Crawler.php#L63

As stated in the [RFC of HTTP/2](https://tools.ietf.org/html/rfc7540#section-8.1.2)  header field names MUST be converted to lowercase.

**Comment by nicolas-grekas** [comment]
Would you mind sending a PR to make that check case insensitive?

**Comment by bytehead** [comment]
Yes for sure! 🙂

**Comment by bytehead** [comment]
I understand now why 4.1.8 is using HTTP/2 and 5.0.2 HTTP/1.0.
4.1.8 is using the `CurlCrawler` while 5.0.2 uses `file_get_contents`.

**Comment by fabpot** [comment]
Thanks for the report. 4.1 is not maintained anymore, you should really upgrade to 5.x instead as 4.1 will not work anymore in a few months (the API used by 4.1 will be shutdown).

**Comment by bytehead** [comment]
Thanks for clarification!
