### ISSUE TITLE
An error occurred: Could not resolve host: security.sensiolabs.org

### ISSUE THREAD

**Issue by ChoppyThing** [sensiolabs/security-checker#149]
Hi,
Is it just me or security.sensiolabs.org is not accessible anymore ?

**Comment by qferr** [comment]
Hi @ChoppyThing. We have the same problem.

**Comment by maxhelias** [comment]
It's now : https://security.symfony.com/

https://twitter.com/fabpot/status/1099994260051582978

**Comment by fabpot** [comment]
I've just closed the old domain. You must use the new one https://security.symfony.com/ by upgrading to version 5 of this library.

**Comment by ChoppyThing** [comment]
Thanks !

**Comment by fancyweb** [comment]
@fabpot You could let this issue open for a while because a lot of people are probably gonna have it.

**Comment by edditor** [comment]
I can't update to version 5 cause of https://github.com/sensiolabs/security-checker/issues/134

**Comment by NathanDePachtere** [comment]
I need help guys ! 

How to update in my case : 
sensiolabs/security-checker        v4.1.8 
sensio/distribution-bundle           v5.0.22
symfony/symfony                          v3.4.21

When i try to update sensiolabs/security-checker I have this error : 
 "sensio/distribution-bundle v5.0.22 requires sensiolabs/security-checker ~3.0|~4.0"

When I try to update sensio/distribution-bundle to 5.0.24 I have this message : 
"Nothing to install or update"

Am I missing something ?

**Comment by shreypuranik** [comment]
> I need help guys !
> 
> How to update in my case :
> sensiolabs/security-checker v4.1.8
> sensio/distribution-bundle v5.0.22
> symfony/symfony v3.4.21
> 
> When I try to update sensiolabs/security-checker I have this error :
> "sensio/distribution-bundle v5.0.22 requires sensiolabs/security-checker ~3.0|~4.0"
> 
> When I try to update sensio/distribution-bundle to 5.0.24 I have this message :
> "Nothing to install or update"
> 
> Am I missing something ?

Does this work? 

\php composer update sensio/distribution-bundle --with-dependencies\

**Comment by RentecJeremy** [comment]
I added https://github.com/sensiolabs/security-checker/pull/152 which will callout the change in domains right on the Readme.md. 

Hopefully this will help save people time searching for why this stopped working (seemingly without warning).

**Comment by rakeev** [comment]
that's a shame
why don't you changed domain also in 4.1 branch??

**Comment by NathanDePachtere** [comment]
> `php composer update sensio/distribution-bundle --with-dependencies`

@shreypuranik it's working ! Thanks ! I didn't know this option ;)

**Comment by fabpot** [comment]
Because only version 5 implements the new protocol. With other versions, you get 429 almost all the time. The reality is that 90% of the requests on our servers end up with 429 HTTP responses. Apparently, the vast majority of users do not even check the results of their calls. That's waste of CPU and bandwidth for everybody.

**Comment by ptrm04** [comment]
Was the only notification about this on twitter and nowhere else? It would be good to put in a note in readme.md on 4.* or something...

**Comment by lfjeff** [comment]
I tried updating to security-checker 5.0 and now I get this message:

>The requested package sensiolabs/security-checker (locked at v4.1.8, required as ^5.0) is satisfiable by sensiolabs/security-checker[v4.1.8] but these conflict with your requirements or minimum-stability

This is a on a new project that was started with Symfony 4.2 Flex. How can I get things working again?

**Comment by lfjeff** [comment]
I don't understand your reference to issue #70 ...

That fixes the URL in the `eyewitness/eye` package.  I'm not using that package and don't know what it does.

My problem is that I'm unable to update the `sensiolabs/security-checker` package.  The error message indicates there is some kind of conflict, but does not give enough information to determine the specific cause.

**Comment by shreypuranik** [comment]
I have added a small note to the existing Symfony-docs entry advising users to use the latest version of the bundle. Thanks for merging @javiereguiluz  https://github.com/symfony/symfony-docs/pull/11139

**Comment by lfjeff** [comment]
I finally manage to fix things on my Symfony 4.2.4 (Flex) system with this command:
`composer require sensiolabs/security-checker:^5.0`

**Comment by fabpot** [comment]
The best is to use the new Symfony CLI (https://symfony.com/download), which does not use the API at all, everything happen locally and usage is straightforward:  `symfony security:check`
