### ISSUE TITLE
An error occurred: Could not resolve host: security.sensiolabs.org.  

### ISSUE THREAD

**Issue by kapigsaan** [sensiolabs/security-checker#150]
Executing script security-checker security:check [KO]
 [KO]
Script security-checker security:check returned with error code 1
!!                                                                         
!!    An error occurred: Could not resolve host: security.sensiolabs.com.  
!!                                                                         
!!

**Comment by maxhelias** [comment]
Same as #149

**Comment by xabbuh** [comment]
this is a duplicate of #149, you need to update the security checker to version 5 to use the new security.symfony.com endpoint

**Comment by kapigsaan** [comment]
thanks.. sorry did not see #149 ^^
