### ISSUE TITLE
-- warning-only argument for console command 

### ISSUE THREAD

**Issue by shreypuranik** [sensiolabs/security-checker#151]
We have integrated the security checker Symfony command as part of our build plan, however, we have found that in the event of a vulnerability being highlighted, the build breaks (as the error code returned is 1, and Bamboo expects 0). 

Would it be possible to introduce an optional parameter -warning-only which results in the highlighted vulnerabilities being returned as is the case at the moment, but with an error code of 0? This way vulnerabilities are still raised, but build plans will not fail.

**Comment by xabbuh** [comment]
I don't believe this would be a proper option for this tool. Instead I would say you should rather ignore the error code in your build if you rather want to treat the security checker this way.

**Comment by fabpot** [comment]
Closing as returning 1 is the proper way to indicate there are issues (and stop the build).
