### ISSUE TITLE
Please support Dev and Prod Environment

### ISSUE THREAD

**Issue by MBurchard** [sensiolabs/security-checker#154]
Hello,

I've installed security-checker as a Dev dependency, because it's not needed on the prod environment.

    composer require --dev sensiolabs/security-checker

It adds '"security-checker security:check": "script"' to the auto-scripts section.

Now, when I prepare the deployment on the hosting environment, I remove all unnecessary dependencies

    cross-env APP_ENV=prod composer install --no-dev --optimize-autoloader

All other scripts in the auto-scripts section do respect the APP_ENV setting and no error messages appear, but the security-checker is started nevertheless...

	yarn run v1.13.0
	$ cross-env APP_ENV=prod composer install --no-dev --optimize-autoloader
	Loading composer repositories with package information
	Installing dependencies from lock file
	Package operations: 0 installs, 0 updates, 9 removals
	  - Removing symfony/web-server-bundle (v4.2.4)
	  - Removing symfony/web-profiler-bundle (v4.2.4)
	  - Removing symfony/var-dumper (v4.2.4)
	  - Removing symfony/stopwatch (v4.2.4)
	  - Removing symfony/profiler-pack (v1.0.4)
	  - Removing symfony/process (v4.2.4)
	  - Removing symfony/polyfill-php72 (v1.10.0)
	  - Removing sensiolabs/security-checker (v5.0.3)
	  - Removing composer/ca-bundle (1.1.4)
	Generating optimized autoload files
	Executing script cache:clear [OK]
	Executing script assets:install public [OK]
	Executing script security-checker security:check [KO]
	 [KO]
	Script security-checker security:check returned with error code 1
	!!  Der Befehl "security-checker" ist entweder falsch geschrieben oder
	!!  konnte nicht gefunden werden.
	!!  
	Script @auto-scripts was called via post-install-cmd
	error Command failed with exit code 1.
	info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

How can that be fixed and is it possible to have that as a default solution?

**Comment by nicolas-grekas** [comment]
Maybe it should be also a prod dep? You still want to check if your prod deps are safe, don't you?

**Comment by nicolas-grekas** [comment]
Note that the security-checker should be now replaced by the Symfony binary!
http://symfony.com/download

**Comment by fabpot** [comment]
I think using the Symfony binary is the way to go.
