### ISSUE TITLE
Can not use security checker - no security namespace

### ISSUE THREAD

**Issue by barell** [sensiolabs/security-checker#159]
Hello,

I wanted to use Symfony security checker and followed instructions from https://symfony.com/doc/current/security/security_checker.html

After installing I can see sensiolabs/security-checker is in version v5.0.3

Now when I run command:
`php bin/console security:check` 

I have following output:
` There are no commands defined in the "security" namespace. `

Am I missing something obvious? I don't use Symfony but only symfony/framework-bundle and few other bundles/components.

**Comment by brunorafaeI** [comment]
Try it php bin/console security:check ! good lucky

**Comment by barell** [comment]
> Try it "php bin/console security:check" good luck!

Sorry, I actually run that command with double colon - corrected my post as it was a misspell. 

It just seems like I'm missing some bundle or config - as this command work if I have a project with symfony/symfony requirement in my composer. 

Maybe would be good to include that in the documentation page?

**Comment by xabbuh** [comment]
The documentation assumes that your application is based on `symfony/skeleton` or `symfony/website-skeleton`. If that's not the case and you are not using Symfony Flex, you will need to register the provided command yourself (see https://github.com/symfony/recipes/blob/master/sensiolabs/security-checker/4.0/config/packages/security_checker.yaml for how it's done in the Flex recipe).

**Comment by barell** [comment]
Ok I see. It makes total sense. I will close this issue.

Thanks!
