### ISSUE TITLE
Failed to open stream : operation failed.

### ISSUE THREAD

**Issue by brunorafaeI** [sensiolabs/security-checker#160]
I have an error after updated my version of symfony/skeleton 3.4.11 to 3.4.23

**command:** 
`php bin/console security:check`

**issue :** 
`An error occurred: file_get_contents(https://security.symfony.com/check_lock): failed to open stream: operation failed.`

Can someone help me?

**Comment by benr77** [comment]
I had this issue, and without upgrading any packages. After a reboot it disappeared so can only presume it was some local DNS issue or something.

**Comment by beechit** [comment]
I have this issue behind a proxy, 

i have this issue:
An error occurred: file_get_contents(https://security.symfony.com/check_lock): failed to open stream: operation failed.

TCP_MISS/200 3193 CONNECT tunnel://security.symfony.com:443/ "proxyuser@proxy" DIRECT/security.symfony.com - ALLOW_CUSTOMCAT_12-POLICY_SRV_AUTH-ID_SRV_AUTH-NONE-NONE-NONE-DefaultGroup-NONE <C_CUST,4.9,-,"-",-,-,-,-,"-",-,-,-,"-",-,-,"-","-",-,-,IW_comp,-,"-","-","Unknown","Unknown","-","-",114.55,0,-,"-","-",-,"-",-,-,"-","-",-,-,"-",-> - Auth Method: BASIC, Auth Wait: 0, DNS Wait: 0, RepScore: 0, Destination: security.symfony.com 443, Time: 2019-09-13 13:48:03, DenialCode: TCP_MISS

How can we solve this ?
