### ISSUE TITLE
Call to undefined function SensioLabs\Security\ctype_digit()

### ISSUE THREAD

**Issue by Nardberjean** [sensiolabs/security-checker#163]
Alpine Linux v3.9
PHP 7.2.18
composer.phar global require --no-progress sensiolabs/security-checker
SensioLabs Security Checker 6.0
$ cd /home/user/.composer
$ vendor/bin/security-checker security:check -vvv
PHP Fatal error:  Uncaught Error: Call to undefined function SensioLabs\Security\ctype_digit() in /home/user/.composer/vendor/sensiolabs/security-checker/SensioLabs/Security/Crawler.php:67
Stack trace:
#0 /home/user/.composer/vendor/sensiolabs/security-checker/SensioLabs/Security/SecurityChecker.php(53): SensioLabs\Security\Crawler->check('composer.lock', 'ansi', Array)
#1 /home/user/.composer/vendor/sensiolabs/security-checker/SensioLabs/Security/Command/SecurityCheckerCommand.php(92): SensioLabs\Security\SecurityChecker->check('composer.lock', 'ansi')
#2 /home/user/.composer/vendor/symfony/console/Command/Command.php(255): SensioLabs\Security\Command\SecurityCheckerCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /home/user/.composer/vendor/symfony/console/Application.php(921): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /home/user/.comp in /home/user/.composer/vendor/sensiolabs/security-checker/SensioLabs/Security/Crawler.php on line 67

**Comment by xabbuh** [comment]
I think you need to install the PHP ctype extension.

**Comment by Nardberjean** [comment]
Thanks that was it.

**Comment by BackEndTea** [comment]
We could also require the symfony ctype polyfill for this project, or require ext-ctype. That way this issue wont happen again

**Comment by Nardberjean** [comment]
Should that be added to the composer.json file?

**Comment by Nardberjean** [comment]
@BackEndTea That look to me the thing to do!

**Comment by Nardberjean** [comment]
It would help for GitLab CI/CD.
