### ISSUE TITLE
Versioned url is broken for v6.x

### ISSUE THREAD

**Issue by c33s** [sensiolabs/security-checker#166]
for ci it is relevant to stick with exact versions, so the link https://get.sensiolabs.org/security-checker.phar is not that useful. in https://github.com/sensiolabs/security-checker/issues/117#issuecomment-384197788 @tucksaun told us the versioned url string.

https://get.sensiolabs.org/security-checker-v5.0.3.phar

this url works fine for the versions 4-5 but not for version 6.

https://get.sensiolabs.org/security-checker-v6.0.1.phar

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
      <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>....</RequestId><HostId>.....</HostId></Error>
```

please reenable versioned urls

**Comment by tucksaun** [comment]
we had an issue in the releasing, thank you @c33s for noticing and reporting it.

we just released 6.0.2 that is available at https://get.sensiolabs.org/security-checker-v6.0.2.phar
