### ISSUE TITLE
Question: How to use SecurityChecker with local database?

### ISSUE THREAD

**Issue by henrikj242** [sensiolabs/security-checker#171]
Hi,
I'm regularly checking a whole bunch of composer.lock files using the SecurityChecker, but I often hit the rate-limit, and would prefer to run the checks on a local copy of the database.

Is it possible to configure the Security checker to use a local copy of the database, just like the symfony command claims to do?

Or, alternatively,  how do I run the `symfony security:check` command in an environment where I do not have permission to run the installer?

Thanks!

**Comment by fabpot** [comment]
You can download the binary here:https://github.com/symfony/cli/releases

**Comment by henrikj242** [comment]
Thanks @fabpot, it's still not clear to me how I make this work with the database from https://github.com/FriendsOfPHP/security-advisories  I expect it must be downloaded to a specific location for the command to work offline?

**Comment by fabpot** [comment]
The DB is downloaded automatically by the command.

**Comment by henrikj242** [comment]
@fabpot great, thanks for clearing that up :-)
