### ISSUE TITLE
Does not handle prerelease versions correctly

### ISSUE THREAD

**Issue by msecker** [sensiolabs/security-checker#173]
Thanks for this great tool.

Unfortunately, the Security Checker reports `propel/propel 2.0.0-alpha10` als insecure due SQL injection,
That not correct, only versions till alpha7 were affected. Since alpha8 this bug was fixed, that was confirmed all the long time by Security Checker

Now, a new version `alpha10` was released and Security Checker thinks it falls into the following constraint, which is wrong behavior I think.
![image](https://user-images.githubusercontent.com/14311931/89012217-19909800-d312-11ea-9754-e81d95469fa0.png)

I think it's a problem with a two-digits pre-release. The Checker calls an endpoint which is a blackbox to us.
Could you check that there?

Just have a look at this issue:
https://github.com/jubianchi/semver-check/issues/77

Thanks!

**Comment by fabpot** [comment]
Closing as this project is not maintained anymore. See https://github.com/fabpot/local-php-security-checker for an open-source software that does the same locally (without any API calls). Feel free to submit a PR there for this bug.
