### ISSUE TITLE
PHP8 compatability

### ISSUE THREAD

**Issue by martinssipenko** [sensiolabs/security-checker#176]
Any plans to support PHP8? Perhaps you would be open to Pull Request?

**Comment by fabpot** [comment]
This should not be used anymore, alternatives are listed at the top of the README file.

**Comment by martinssipenko** [comment]
Oh okay, may I suggest adding a better notification that this should not be used at the top of README file? Currently, it only suggesting symony CLI as an alternative without mentioning that this should not be used.
