### ISSUE TITLE
Make output more verbose

### ISSUE THREAD

**Issue by agrandville** [sensiolabs/security-checker#177]
I use security:check to audit vulnerabilities in several projects.
Currently the output is limited to this
```
C:\dev\audit\fpay-wallet>symfony security:check
Symfony Security Check Report
=============================

No packages have known vulnerabilities.

Note that this checker can only detect vulnerabilities that are referenced in the security advisories database.
Execute this command regularly to check the newly discovered vulnerabilities.
``` 

Is there any option to get

-  the full package list with for each name, version, vulnerability state and details if need.
```
[11/19] - pkg:bower/angular-touch@1.7.5 - No vulnerabilities found!
[12/19] - pkg:bower/angular-ui-router@1.0.11 - No vulnerabilities found!
[13/19] - pkg:bower/angular@1.7.5 - 1 vulnerability found! ....
```

- The vulnerability database ID (Date of update and version)
- Symfony security tool version and report date

json or text output choice would be a must

Thanks

**Comment by fabpot** [comment]
Closing as this project is not maintained anymore. See https://github.com/fabpot/local-php-security-checker for an open-source software that does the same locally (without any API calls).
