### ISSUE TITLE
The web service failed for an unknown reason (HTTP 502)

### ISSUE THREAD

**Issue by delpes** [sensiolabs/security-checker#178]
I am currently getting the above error running the security checker with the option _security:check_

I tried with difference composer.lock files from different projects on different machines.

I was yet unable to find out which web-call fails.

**Comment by Coffelius** [comment]
This is happening for me too and it's making my pipelines to fail :O

**Comment by delpes** [comment]
Looks like _https://security.symfony.com/check_lock.json_ has currently an issue.

I tried with the web-interface offered at: [https://security.symfony.com/](https://security.symfony.com/) which fails with a 502 Bad Gateway Error

**Comment by arturslogins** [comment]
Same issue in my pipeline

**Comment by artyuum** [comment]
It's fixed now.

**Comment by delpes** [comment]
Closing issues as the service is available again
