### ISSUE TITLE
Option to return 0 regardless of vulnerabilities

### ISSUE THREAD

**Issue by glye** [sensiolabs/security-checker#179]
Currently security-checker returns 1 if a vulnerability is found. We could use an option to return 0 regardless of any vulnerabilities found. This is to ensure that scripted deployments do not break. Manual installs would still see the message.

Something like `--no-fail` or `--continue`. I can do a PR, if there is any chance it might be accepted.

**Comment by fabpot** [comment]
Why use something like `|| true`?

**Comment by glye** [comment]
You mean why _not_ use that? We do. Problem is, I couldn't get this to work with the `"security-checker security:check": "script"` command in auto-scripts, so I had to move it into both the "post-*-cmd" sections, as `"@php bin/security-checker security:check || true"`, where it's duplicated now. Would be better to have just one line.

**Comment by fabpot** [comment]
Closing then as I don't see why we should have a workaround here. The same is true for any other commands. Thanks for proposing.

**Comment by glye** [comment]
To clarify, if I add `|| true` to the command in auto-scripts, it will not show any output. The warnings about vulnerabilities are not shown. We want to see the warnings, but not break execution.

The duplicated commands in "post-*-cmd" works, so fair enough. Thanks for answering.
