### ISSUE TITLE
Please add proxy support for curl

### ISSUE THREAD

**Issue by strietzel** [sensiolabs/security-checker#19]
It would be very nice to specifiy a proxy via the command line options, so that it is set as a curl_opt.

**Comment by matthieuxyz** [comment]
This is 3.5 years old and still an issue.

Please, life behind a proxy is already annoying. Hundred of softwares break and/or are hard to configure to work with the proxy. And when working on an university project or in a company, the proxy just can't be bypassed. Adding proxy support would really make my life easier.

You switched from Curl to file_get_contents, nice. Proxy is easy to setup with this:
http://stackoverflow.com/a/1336419/6612380

All you have to do is read config from "http_proxy" env variable, which can be done with this:
https://github.com/oscarotero/env

I can even make a pull request if you're not afraid of my ugly code...

**Comment by tucksaun** [comment]
The thing is, all the requests are going trought HTTPS, so you probably just have to set `HTTPS_PROXY` instead of `HTTP_PROXY` and PHP should use it.

**Comment by matthieuxyz** [comment]
$HTTP_PROXY and $http_proxy are both set and file_get_contents() doesn't seems to read them.

Other PHP tools like composer are working perfectly well, though. I believe that file_get_Contents() need the proxy parameters to be passed when called in the context variable.

**Comment by tucksaun** [comment]
@matthieuxyz please note I put an **S** :)
`security.sensiolabs.org` is exclusively reachable over TLS so `HTTP_PROXY` (or `http_proxy`) won't be used by `file_get_contents` or `curl` in this context but "HTTP**S**_PROXY" will.

**Comment by matthieuxyz** [comment]
Oops. Sorry, I edited my previous post.

I confirm that all FOUR unix variables are set. Upper and lower cases http and https, with current user and root. I can "echo $https_proxy" and get the expected result. They were set since the very beginning, composer is working, security-checker isn't.

**Comment by morsok** [comment]
Having the same issue and needed to disable my CI job :/

Anything I can do to help ?

**Comment by fabpot** [comment]
The best is to use the new Symfony CLI (https://symfony.com/download), which does not use the API at all, everything happen locally and usage is straightforward:  `symfony security:check`
