### ISSUE TITLE
[META] Convert into composer extension?

### ISSUE THREAD

**Issue by patcon** [sensiolabs/security-checker#24]
I'm actually really surprised how niche this tool seems to be, and the number of vendors supporting it is much lower than I would have expected, given how freaking *awesome* it is. I'm wondering what people think about rearchitecting this tool as a composer extension that appears inline with composer commands.

Off-hand, these would seem to be the benefits:
- **Easier discoverability.** Something like `composer-audit` (or any other arbitrary name) would be easier to find for those searching for composer-related extension and tools.
- **Better branding of security.** Composer is the defacto PHP package manager. Many would never consider starting a project without leveraging it. I believe that using Composer's "brand" would help this "wouldn't leave home without it" mentality extend into the security realm.
- **Ability to insert security into dev workflow.** If composer is a dep, it would be much more straightforward to add security warnings and notices from this tool into regular user workflows involving `composer install` or `composer update`. The less "special-snowflake" commands that users need to run to be presented important security information, the better :)

Thoughts?

cc: @stof @fabpot @Seldaek @greggles

**Comment by DavidePastore** [comment]
Hi @patcon, I just created [composer-audit plugin](https://github.com/DavidePastore/composer-audit), as you suggest. Let me know if it is what you thought.

**Comment by stof** [comment]
there is a composer metapackage which is generated based on the same advisory database to prevent using affected packages: https://packagist.org/packages/roave/security-advisories
This does not require any Composer plugin (just require the package)

**Comment by DavidePastore** [comment]
@stof Thanks for reporting this. :+1: 
Differences between `roave/security-advisories` and `davidepastore/composer-audit` are:
* `composer-audit` let you install whatever you want (it simply shows alerts) and `roave/security-advisories` fails in that case;
* `composer-audit` takes information directly from security advisories and `roave/security-advisories` has a commit based repository between that;
* `composer-audit` is based on `sensiolabs/security-checker` and `roave/security-advisories` doesn't require any Composer plugin (as you said).

**Comment by stof** [comment]
@DavidePastore sensiolabs/security-checker probably also has a step between the https://github.com/FriendsOfPHP/security-advisories and the online security checker (I doubt that the webservice is loading the files from github on each request)
And you missed one point: ``composer-audit`` introduces security.sensiolabs.org as a point of failure in your ``composer install`` (while only github downloads are when using ``roave/security-advisories`` and locking your dependencies)

**Comment by DavidePastore** [comment]
@stof I agree and I get your point but I'm not a fan of redundancy.

**Comment by stof** [comment]
redundancy ?

**Comment by DavidePastore** [comment]
Make a [commit everytime another repository updates](https://github.com/Roave/SecurityAdvisories/commits/master) is what I call redundancy of data. It's just copying values and transform them in another format.

**Comment by stof** [comment]
@DavidePastore the same is true for the sensiolabs security checker, except that the update of the webservice database happens in a private location

**Comment by DavidePastore** [comment]
To have more info on this we should ask to @fabpot .

**Comment by fabpot** [comment]
I'm closing this one as I like to have more than one options. This repo and roave/security-advisories and complementary and one can use one or the other depending on his workflow.

**Comment by stof** [comment]
To improve the flow of updating ``roave/security-advisories``, @Ocramius may build a small webhook triggering the update of the conflict rules (generating them is already automated) and ask @fabpot to register it as a webhook on the security advisory database repository btw.

**Comment by Ocramius** [comment]
@stof I can probably simply trigger my builds via travis-ci. Need to experiment with it, but I'd rather rely on an existing tool than deploying my own hook somewhere.

Otherwise, brutal polling :-|

**Comment by stof** [comment]
@Ocramius you would have to make this build in the Travis-CI build of the security-advisory database though, which looks really weird to me
