### ISSUE TITLE
plug tests, travis.yml in particular please, because behavior is different in hhvm

### ISSUE THREAD

**Issue by cordoval** [sensiolabs/security-checker#28]
hhvm does not see a .lock
https://travis-ci.org/gushphp/gush/jobs/30379316

php 5.5 sees a .lock
https://travis-ci.org/gushphp/gush/jobs/30379315

same repo

![screenshot 2014-07-20 01 54 35](https://cloud.githubusercontent.com/assets/328359/3636720/bfbd8c9e-0fda-11e4-8848-4b9e124b2142.png)

**Comment by fabpot** [comment]
Closing as there is no feedback.

**Comment by cordoval** [comment]
yep sorry about this, we are not using hhvm anymore so it is not a problem anymore.
