### ISSUE TITLE
No lock!

### ISSUE THREAD

**Issue by TxReplay** [sensiolabs/security-checker#33]
Hi, 

I'm on Symfony 2.5.5 and when I try to install my website locally on a Mac, it keeps returning the error `InvalidArgumentException: no lock!`

Despite of this, I can upload my composer.lock on the website Checker without problems. I don't have this problems on Windows, Ubuntu and Debian.

Any guess ?

**Comment by xabbuh** [comment]
When exactly does this happen? What steps need to be done to reproduce your issue?

**Comment by TxReplay** [comment]
When I try to go to my website, this is very weird, I don't do anything wrong or different than a Windows/Linux install... It seems like the Security Checker can't send my composer.lock to the website checker, it return a 400 error.

**Comment by xabbuh** [comment]
Does this mean you try to send your project's `composer.lock` file to the security checker every time you visit your web site? Can you show the related code?

**Comment by fabpot** [comment]
Closing as there is no more feedback.
