### ISSUE TITLE
SSL CA issue on CentoOS

### ISSUE THREAD

**Issue by mjgorman** [sensiolabs/security-checker#34]
```
An error occurred: Peer certificate cannot be authenticated with known CA certificates.
```
Getting SSL errors with latest centOS CA, works fine locally on my mac. Anyone seen this issue before?  Tried -vvv and got no additional information. Tried as our build user and root, same error so doesn't seem to be permissions.

**Comment by mjgorman** [comment]
```
-curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, 1);
+curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
```
makes it work, was the 1 supposed to be a false? Or a level of verification? not familiar with curlopts for php.

**Comment by moffe42** [comment]
Same issue on Amazon Linux.

**Comment by tommy-muehle** [comment]
Same issue here on Debian 7.8 since yesterday. But message is a litte bit different:
```
An error occurred: server certificate verification failed. CAfile: /tmp/sls2iqX2P CRLfile: none. 
```
We used the Phar in version "2.0".

**Comment by fabpot** [comment]
Update to the 2.0.2 version, where this issue has been fixed.
