### ISSUE TITLE
Problem with curl/certificate since 2.0.4: An error occurred: error setting certificate verify locations

### ISSUE THREAD

**Issue by bskart** [sensiolabs/security-checker#42]
I am getting this error when i try to run the security-checker:

```
An error occurred: error setting certificate verify locations:
CAfile: /home/.../vendor/sensiolabs/security-checker/SensioLabs/Security/Resources/security.sensiolabs.org.crt
CApath: /etc/ssl/certs.  
```
when trying to run the security checker, it fails on my developer machine and the build-server, --verbose does not provide any additional output.

Only page with the same error i found with google so far:
https://insight.sensiolabs.com/projects/0e707629-c858-4b6e-9fe0-f9e6dca1ad49/analyses/20

Going back to 2.0.3 solves the problem for me for now.

Happens to me on:

Linux Mint Mate with PHP 5.6.9 (dotdeb)
Linux Debian 7.8 with PHP 5.6.9 (dotdeb)

**Comment by whisller** [comment]
Same here. Debian 7.4 PHP 5.6.8. Works fine for `2.0.3`

**Comment by peikk0** [comment]
There is an extra leading space before "-----BEGIN CERTIFICATE-----", removing it solves the problem.

**Comment by acrozes** [comment]
The error is fixed for me

**Comment by michaelcullum** [comment]
Although I'm now getting `An error occurred: SSL certificate problem: unable to get local issuer certificate.`

**Comment by bskart** [comment]
For me on both systems everything works fine with 2.0.5.

@michaelcullum sound like https://github.com/sensiolabs/security-checker/pull/38

**Comment by xabbuh** [comment]
@bskart Can you then please close this issue?

**Comment by bskart** [comment]
Yes
