### ISSUE TITLE
Will this checker support environment checking? like php, apache, nginx version checking

### ISSUE THREAD

**Issue by leric** [sensiolabs/security-checker#53]
The running environment is also an important factor of secure system, like the version of php, nginx, apache, pecl extension. I know that's totally different functionality other than checking composer.lock, but it's really fit for this project as a security checker for php project dependencies.

**Comment by fabpot** [comment]
We are only focused on Composer deps. The main reason is that a `composer.lock` file is enough to test for security issues, and this file does not depend on the environment or configuration (which can be different depending on your machine, prod, test, dev, staging, ...). Checking problems in PHP, nginx, or anything else is a totally different problem with existing solutions; you can for instance only test that on the production servers, and without access to it, that's almost impossible.
