### ISSUE TITLE
Problem with open_basedir

### ISSUE THREAD

**Issue by guilhermednt** [sensiolabs/security-checker#56]
In environments where `open_basedir` is set, the following occurs:

`curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set`

The origin of this is [here](https://github.com/sensiolabs/security-checker/blob/master/SensioLabs/Security/Crawler/CurlCrawler.php#L46).

**Comment by w3l** [comment]
+1

**Comment by fabpot** [comment]
fixed in 116027b
