### ISSUE TITLE
Add "security:blindSpot"

### ISSUE THREAD

**Issue by christian-weiss** [sensiolabs/security-checker#57]
This command should list all packages from composer.lock that are NOT listed in security advisories database. 

This feature request comes with feature request for security advisories database: add "tracked" packages to your git repo, even if there is no security issue at the moment:
"someTrackedVendor" / "someTrackedPackage" / .gitkeep

(tracked means that you checked this package for security advisories)

**Comment by fabpot** [comment]
Out of the scope of this repository.
