### ISSUE TITLE
Add the ability to downgrade an advisory to a warning

### ISSUE THREAD

**Issue by relaxnow** [sensiolabs/security-checker#59]
We have a use case where we're using Zend_Mail for some mail parsing however this version has a vulnerability with regards to mail *sending*. We don't send mail with Zend_Mail, we use Swiftmailer for that.
Unfortunately upgrading to a newer version of Zend_Mail is not possible as they refactored the component disallowing using it for mail parsing.

Keeping a vulnerable component around is dangerous (someone might use it wrong in the future) but we may not have a choice.

Now I would suggest adding an ability to 'downgrade' a vulnerability from an 'error' (that blocks builds) to a warning that emits output but still gives exit code 0.

**Comment by relaxnow** [comment]
@jvdschraaf could you look into this?

**Comment by fabpot** [comment]
I understand your situation, but the goal of this tool is to "just" report vulnerabilities. Of course, with the API, you could implement this kind of feature quite easily, or by just extending the classes provided by this repo.
