### ISSUE TITLE
Class 'SensioLabs\Security\SecurityChecker' not found

### ISSUE THREAD

**Issue by Nitinrahgav** [sensiolabs/security-checker#60]
When i run cron command it shows 
Fatal error: Class 'SensioLabs\Security\SecurityChecker' not found in C:\wamp\www\nnn\profiles\octopus_video\modules\composer_manager\composer_manager_sa\composer_manager_sa.module on line 83
![cron](https://cloud.githubusercontent.com/assets/20492278/16896848/73321932-4bbd-11e6-9c6d-8680119f56bd.png)

**Comment by xabbuh** [comment]
@Nitinrahgav How did you install the package?

**Comment by fabpot** [comment]
Closing as there is no feedback.
