### ISSUE TITLE
Security Checker doesn't work if a corporate SSL certificate gets injected

### ISSUE THREAD

**Issue by xelaris** [sensiolabs/security-checker#67]
I want to use the security checker within an environment where a corporate SSL certificate gets injected into HTTPS traffic.

Since the CA file is bundled with security checker (especially in the phar), it seems there is no way to get it work in such an environment.

I see two options:

1. Adding an option to disable the usage of the bundled CA file, falling back to the systems one (precisely don't calling `curl_setopt($curl, CURLOPT_CAINFO, ...)`)
2. Add an argument to enable the usage of a custom CA file (precisely calling `curl_setopt($curl, CURLOPT_CAINFO, ...)` with a custom file.

Are there preferences? I would like to submit a PR for this.

For the reference: The bundled ca file was added in #14 to fix a SSL certificate problem on windows.

**Comment by maddhatter** [comment]
Setting a `SSL_CERT_FILE` environment variable should let you specify a custom CA. (It's working for me at least).

The `composer/ca-bundle` package [checks for that variable and prioritizes it](https://github.com/composer/ca-bundle/blob/master/src/CaBundle.php#L72).

**Comment by xelaris** [comment]
Indeed that should work now. The descriped issue was fixed by making use of `composer/ca-bundle` in PR #77. Thank you @maddhatter for pointing that out.

There shouldn't even a need of setting the `SSL_CERT_FILE` environment variable in my case, because `composer/ca-bundle` can locate and provide the CA bundle of the system, which includes the mentioned corporate SSL certificate.
