### ISSUE TITLE
Download link is insecure

### ISSUE THREAD

**Issue by aucuparia** [sensiolabs/security-checker#68]
Please make the security-checker.phar available over HTTPS and/or provide (signed) hashes.

**Comment by halfer** [comment]
One way is to do a manual install using Composer, and obtain the source over HTTPS:

    mkdir /root/symfony && \
    cd /root/symfony && \
    wget https://github.com/sensiolabs/security-checker/archive/4.1.zip && \
    unzip 4.1.zip && \
    cd /root/symfony/security-checker-4.1 && \
    php /tmp/composer.phar install

**Comment by c33s** [comment]
can we please have a secure download link for a security tool? :)

**Comment by thomaskonrad** [comment]
This is indeed kind of weird. This is a security tool, and this issue was opened about 1.5 years ago!

**Comment by theofidry** [comment]
@fabpot would you be fine with uploading the PHAR to the releases as an artefact? This way the download link would be HTTPS. This could be done by setting up Travis with an upload artefact on releases.

**Comment by Aerendir** [comment]
Any news here?

I'm trying to downlad the phar file with [`Phive`](https://github.com/phar-io/phive) but it is not possible as the URL is not secure.

**Comment by fabpot** [comment]
HTTPS is now used for the phars.

**Comment by theofidry** [comment]
❤️
