### ISSUE TITLE
Security checker does not check dev dependencies

### ISSUE THREAD

**Issue by alcaeus** [sensiolabs/security-checker#71]
Having this minimal `composer.json`:
```json
{
    "require-dev": {
        "squizlabs/php_codesniffer": "2.7.1",
        "sensiolabs/security-checker": "^4.0"
    }
}
```

Running the security checker yields no error, even though a vulnerable version of phpcs is installed:
```
$ vendor/bin/security-checker security:check

Symfony Security Check Report
=============================

 // Checked file: <path>/composer.lock

                                                                                                                        
 [OK] No packages have known vulnerabilities.                                                                           
                                                                                                                        

 ! [NOTE] This checker can only detect vulnerabilities that are referenced in the SensioLabs security advisories        
 !        database. Execute this command regularly to check the newly discovered vulnerabilities.                       
```

Moving the requirement to php_codesniffer to `require` instead of `require_dev` fixes the problem, which leads me to conclude that dev dependencies are not checked. Given that the tools deals with security issues which might also affect developer machines, the tool should not exclude dev dependencies.

**Comment by fabpot** [comment]
fixed now

**Comment by alcaeus** [comment]
@fabpot tested it again and the issue is still there, even with the latest version of `sensiolabs/security-checker` (v4.1.2). Am I missing something?

**Comment by fabpot** [comment]
Should have been fixed by https://github.com/sensiolabs/security-checker/blob/master/SensioLabs/Security/Crawler/BaseCrawler.php#L63

**Comment by fabpot** [comment]
hmmm, sorry, that's not supported by the current server, but by the new one which is not yet available. Reopening for now. But that will be fixed soon(tm).

**Comment by fabpot** [comment]
Sorry for the confusion. I should have said: works for me on the new server that you don't have access to yet :)

**Comment by alcaeus** [comment]
@fabpot gotcha, no worries. Thanks for fixing! 🍻
