### ISSUE TITLE
SSL Error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by binarious** [sensiolabs/security-checker#73]
Since this morning I get the following error while running `php bin/console security:check` on different machines:
```
An error occurred: SSL certificate problem: unable to get local issuer certificate.
```
It worked yesterday.

**Steps to reproduce**
```
symfony new sec-test
cd sec-test
php bin/console security:check
```

**Tested Envs**
- MacOS 10.12.4, openssl 1.0.2k, PHP 7.0.17
- Fedora 25, openssl 1.0.2k, PHP 7.1.3

**Comment by tomnijboer** [comment]
Same error here

**Comment by fabpot** [comment]
That's because we've just moved to Let's Encrypt. Expect new versions later today.

**Comment by catchamonkey** [comment]
We run the security checker in our travis builds so this is stopping anything from passing unfortunately.
Do you know when the new versions will be published today?

**Comment by fabpot** [comment]
4.0.3 released.

**Comment by catchamonkey** [comment]
> 4.0.3 released.

👏  Many thanks for being so speedy!

**Comment by fabpot** [comment]
3.0.6 out

**Comment by jenkoian** [comment]
4.0.3 (and 3.0.7) don't seem to work for me on travis, any idea why this may be happening? It did fix the issue locally for me. Example builds: https://travis-ci.org/jenkoian/flysystem-gaufrette/builds/216655338 possibly a travis issue(?) so did raise an issue there too: https://github.com/travis-ci/travis-ci/issues/7539

**Comment by javiereguiluz** [comment]
We're facing the same problem as @jenkoian in the Symfony Demo repo: https://travis-ci.org/symfony/symfony-demo/jobs/216671580#L349  `An error occurred: gnutls_handshake() failed: A TLS fatal alert has been received..`

**Comment by jenkoian** [comment]
Think this and https://github.com/sensiolabs/security-checker/issues/75 are the same thing, so probably worth closing one of them. Actually this one is already closed, so maybe just use that other one?

**Comment by andig** [comment]
My problem is that I've using http://get.sensiolabs.org/security-checker.phar on travis and that still seems to download v3.0.
