### ISSUE TITLE
A TLS fatal alert has been received..

### ISSUE THREAD

**Issue by gabeguz** [sensiolabs/security-checker#75]
Running `security-checker` as part of my CI pipeline, this morning I started seeing TLS errors.  Updated to the latest version (4.0.3) and they went away on my local, but in circleci I'm still seeing: 

```
ubuntu@box1304:~/ecom-middleware$ ./vendor/bin/security-checker -vvv security:check ./composer.lock

  An error occurred: gnutls_handshake() failed: A TLS fatal alert has been received..
```
Not sure why.  Any ideas?

**Comment by EAnushan** [comment]
I'm getting:

```
An error occurred: SSL certificate problem: unable to get local issuer certificate.
```

**Comment by jjanusch** [comment]
We've been receiving

> An error occurred: SSL: certificate verification failed (result: 5).

for the last few days.

**Comment by graemechapman** [comment]
I'm getting 
```
 An error occurred: gnutls_handshake() failed: A TLS fatal alert has been received.. 
```
when running through Travis CI, since updating to 4.0.3 yesterday.

**Comment by jamyouss** [comment]
Have an issue with the handshake maybe related to the TLS problem:
`  An error occurred: Cannot communicate securely with peer: no common encryption algorithm(s)..`

**Comment by gabel** [comment]
Same here on travis ci environment.

```bash
$ ~/.composer/vendor/sensiolabs/security-checker/security-checker security:check composer.lock
                                                                                       
  An error occurred: gnutls_handshake() failed: A TLS fatal alert has been received..  
```

**Comment by kareltrcalek** [comment]
Hi, we are also suffering from this Issue:

```
0.42s$ ~/.composer/vendor/sensiolabs/security-checker/security-checker security:check composer.lock
                                                                                       
An error occurred: gnutls_handshake() failed: A TLS fatal alert has been received..  
                                                                                       
The command "~/.composer/vendor/sensiolabs/security-checker/security-checker security:check composer.lock" exited with 1.
```

running currently v.4.0.3. 

Is this issue related to change to LetsEncrypt https://github.com/sensiolabs/security-checker/commit/04bb87f5bd28a7d6ce7f4a4d1d6b94b3c1aa8dae ?


Can you please quickly fix this issue?

**Comment by tucksaun** [comment]
Hi everyone,
It's probably because your OpenSSL CA bundle is empty.
Could you try #77 ? it should fix your issues.

**Comment by kareltrcalek** [comment]
Hi @tucksaun 
can you build a version or tag with this bug-fix? We can only install it via composer

**Comment by catchamonkey** [comment]
> can you build a version or tag with this bug-fix? We can only install it via composer

This is possible using composer aliasing.

Add the source to your repositories block

```
"repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:tucksaun/security-checker.git"
        }
    ],
```

And then alias in your require-dev

```
"require-dev": {
    "sensiolabs/security-checker": "dev-fix-ssl-issues as 4.0.4"
},
```

**Comment by moffe42** [comment]
I am still seeing this issue despite running 4.0.4.

Running on Amazon linux

**Comment by graemechapman** [comment]
@moffe42 have you tried using an http endpoint as posted [here](https://github.com/sensiolabs/security-checker/pull/77#issuecomment-290733113)

**Comment by moffe42** [comment]
@graemechapman That worked, but that is not a good solution. It seems due to the fact that Amazon Linux is using NSS instead of OpenSSL as default.

**Comment by theofidry** [comment]
Hi, the issue is still occurring on Travis CI:

```
PHP 7.1.3 (cli) (built: Mar 17 2017 12:34:14) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.3, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans

sensiolabs/security-checker           v4.0.4

Build language: php
Build group: stable
Build dist: precise
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
Linux Version
3.13.0-29-generic
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
```

**Comment by tarlepp** [comment]
Yep having the same problem within TravisCI, any solutions how to fix this ?

**Comment by fabpot** [comment]
Have you tried to use the HTTP endpoint? See https://github.com/sensiolabs/security-checker/pull/77#issuecomment-290733113

**Comment by tarlepp** [comment]
@fabpot sorry but I can't get any heads or tails on that issue comment :( What to do, where, etc...

**Comment by fabpot** [comment]
`security-checker security:check --end-point=http://security.sensiolabs.org/check_lock`

**Comment by tarlepp** [comment]
so that change is to make to `composer.json` file ?

**Comment by theofidry** [comment]
@tarlepp really not sure to understand your question, fabpot gave your the command: you only need to add the option `--end-point=http://security.sensiolabs.org/check_lock`

**Comment by tarlepp** [comment]
@theofidry it take a while to understand that command is descriped in `composer.json` file.
