### ISSUE TITLE
Contrast on "disclaimer" hard to read

### ISSUE THREAD

**Issue by mfn** [sensiolabs/security-checker#76]
The "white on yellow" disclaimer is hard to read:

![image](https://cloud.githubusercontent.com/assets/87493/24488535/b9c679d2-1517-11e7-8082-674d40d1b9dc.png)

I'm additionally running f.lux (can't "capture" that on the screenshot) and this almost looks like a yellow rectangle with nothing in it.

SensioLabs Security Checker 3.0
OSX: 10.12.4
f.lux: 37.7
iTerm2: 3.0.15

**Comment by fabpot** [comment]
Depends on your config. Closing.
