### ISSUE TITLE
Error after switching to Let's Encrypt certificate

### ISSUE THREAD

**Issue by moffe42** [sensiolabs/security-checker#78]
The latest version 4.0.4 does not work on Amazon Linux. You get the following error

```
bash-4.2$ ./vendor/bin/security-checker -vvv security:check ./composer.lock

An error occurred: Cannot communicate securely with peer: no common encryption algorithm(s)..
```
This seems to be do to the fact that cURL via PHP on Amazon Linux uses NSS and not OpenSSL.

**Comment by fabpot** [comment]
Closing this old issue as there is nothing I can do about it.
