### ISSUE TITLE
certificate verify failed

### ISSUE THREAD

**Issue by spongedoc** [sensiolabs/security-checker#79]
We have a problem, after the last update. If i try to run the security:check symfony command, we recive this error:

> An error occurred: . 

And this is the description in the app/logs/dev.log:

> [2017-04-04 11:17:46] php.DEBUG: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed {"type":2,"file":"/home/thuja/vendor/sensiolabs/security-checker/SensioLabs/Security/Crawler/FileGetContentsCrawler.php","line":46,"level":28928} []
> [2017-04-04 11:17:46] php.DEBUG: file_get_contents(): Failed to enable crypto {"type":2,"file":"/home/thuja/vendor/sensiolabs/security-checker/SensioLabs/Security/Crawler/FileGetContentsCrawler.php","line":46,"level":28928} []
> [2017-04-04 11:17:46] php.DEBUG: file_get_contents(https://security.sensiolabs.org/check_lock): failed to open stream: operation failed {"type":2,"file":"/home/thuja/vendor/sensiolabs/security-checker/SensioLabs/Security/Crawler/FileGetContentsCrawler.php","line":46,"level":28928} []
> 
The config:
docker image, ubuntu 16.04 LTS
php 5.6

**Comment by bbrala** [comment]
Hmm, since april? Thats no good...

**Comment by mjrider** [comment]
it looks more like 'again'
