### ISSUE TITLE
Internal error (HTTP 500) 

### ISSUE THREAD

**Issue by rev42** [sensiolabs/security-checker#80]
Since 15th of April, when executing following command, 

> vendor/sensiolabs/security-checker/security-checker  security:check

we get the error:
> The web service failed for an unknown reason (HTTP 500).

**Comment by helios-ag** [comment]
Faced same issue

**Comment by issei-m** [comment]
Same issue.

**Comment by fabpot** [comment]
Should be fixed now

**Comment by helios-ag** [comment]
Thanks @fabpot!

**Comment by issei-m** [comment]
@fabpot I could confirm fixed. Thank you!

**Comment by ddproxy** [comment]
Security-checker is hanging for me, no reported errors (yet).

**Comment by rev42** [comment]
Fix verified!
