### ISSUE TITLE
SSL certificate is expired

### ISSUE THREAD

**Issue by avant1** [sensiolabs/security-checker#84]
@fabpot certificate for https://security.sensiolabs.org/ was valid until Tue, 27 Jun 2017 06:28:00 UTC
LetsEncrypt certs are issued for 3 months, but there are ways to make cert updates automatically.

**Comment by brammittendorff-dd** [comment]
Yes, we keep on getting issues with the `security-checker -n security:check` command. Every time the cert expires.

**Comment by tomnijboer** [comment]
Same problem here, blocking all the builds of us

**Comment by frenck** [comment]
Seriously? All build fail and are blocked.

A security tool that does not have the proper security in place, isn't that ironic? 😄

**Comment by Marascon** [comment]
This is quite limiting on the workflow, Extend it and Google how to auto extend, it will prevent this...

**Comment by DWDRobVisser** [comment]
/opt/letsencrypt/letsencrypt-auto would be a nice start to prevent this from happening, perhaps. :)

**Comment by avant1** [comment]
You can temporarily disable this check if it is blocking you.
If you haven't updated Composer dependencies and you regularly run builds it should be safe.

**Comment by frenck** [comment]
@avant1 I'm sorry but I don't feel like updating 50+ GitLab CI configuration files in 50+ repositories "temporarily".....

**Comment by tucksaun** [comment]
Hi everyone,

It should be fixed now.

Let me know if you encounter any issue.

**Comment by frenck** [comment]
_Reverting 50+ repo GitLab CI edits..._ 😅 

Thanks for the quick fix @tucksaun 👍

**Comment by Addvilz** [comment]
Here it is, folks. Yet another case of 3rd party service (!!!) failure blocking builds and delivery. Cmoon, I thought we have learned this by know.

**Comment by theofidry** [comment]
@Addvilz:

- renting doesn't really help 
- it's supposed to be fixed now
- you can always skip that check

**Comment by Addvilz** [comment]
@theofidry I think you misunderstood me. I was pointing out this is a non-issue, as it is ill advised to rely on 3rd party services to be always up during build and delivery in the first place. This time it was avoidable failure. Next time it might not be and so we will get a ticket every time seccheck is down? What.

**Comment by theofidry** [comment]
@Addvilz apologize for the misread then 🙇
