### ISSUE TITLE
Undefined index: time when running security:check with version 4.1.0

### ISSUE THREAD

**Issue by venyii** [sensiolabs/security-checker#88]
Hey there,

I wanted to upgrade the security-checker in a project, but I'm currently getting a `[Symfony\Component\Debug\Exception\ContextErrorException] Notice: Undefined index: time` exception when running the `security:check` command.

The problem seems to be a [path repository](https://getcomposer.org/doc/05-repositories.md#path) which may have `dev` in the version field but those don't have a `time` field.

Tested this with a sample composer.json and the resulting package in the .lock is:
```
{
    "packages": [
        {
            "name": "my/package",
            "version": "dev-master",
            "dist": {
                "type": "path",
                "url": "../pkg",
                "reference": "4c8cf97589f5ecc12e5ad7ef7b65d480685dbc35",
                "shasum": null
            },
            "type": "library"
        }
    ],
```

Tested with:
`pkg/composer.json`
```
{
  "name": "my/package",
  "version": "dev-master"
}
```

`main/composer.json`
```
{
  "repositories": [
    {
      "type": "path",
      "url": "../pkg"
    }
  ],
  "require": {
    "my/package": "*@dev",
    "sensiolabs/security-checker": "4.1.0"
  }
}
```

Testing the resulting composer.lock:
```
$ ./vendor/bin/security-checker security:check composer.lock
PHP Notice:  Undefined index: time [...]
```

PHP 7.1.5, Composer 1.4.2

**Comment by fabpot** [comment]
fixed

**Comment by venyii** [comment]
Thanks!
