### ISSUE TITLE
PHP Warning:  Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by cvuorinen** [sensiolabs/security-checker#91]
When using the latest version of security checker (4.1.2)  I get the following PHP warning.

I guess it has something to with the actual lock file since it only happens for one certain project out of all that I have tried (about a dozen or so).

```
PHP Warning:  Invalid argument supplied for foreach() in 
./vendor/sensiolabs/security-checker/SensioLabs/Security/Crawler/BaseCrawler.php on line 74
```

<details>
 <summary>Full stack trace</summary>

```
PHP Stack trace:
PHP   1. {main}() ./vendor/sensiolabs/security-checker/security-checker:0
PHP   2. Symfony\Component\Console\Application->run() ./vendor/sensiolabs/security-checker/security-checker:32
PHP   3. Symfony\Component\Console\Application->doRun() ./vendor/symfony/console/Application.php:117
PHP   4. Symfony\Component\Console\Application->doRunCommand() ./vendor/symfony/console/Application.php:186
PHP   5. SensioLabs\Security\Command\SecurityCheckerCommand->run() ./vendor/symfony/console/Application.php:791
PHP   6. SensioLabs\Security\Command\SecurityCheckerCommand->execute() ./vendor/symfony/console/Command/Command.php:256
PHP   7. SensioLabs\Security\SecurityChecker->check() ./vendor/sensiolabs/security-checker/SensioLabs/Security/Command/SecurityCheckerCommand.php:83
PHP   8. SensioLabs\Security\Crawler\DefaultCrawler->check() ./vendor/sensiolabs/security-checker/SensioLabs/Security/SecurityChecker.php:52
PHP   9. SensioLabs\Security\Crawler\CurlCrawler->check() ./vendor/sensiolabs/security-checker/SensioLabs/Security/Crawler/DefaultCrawler.php:31
PHP  10. SensioLabs\Security\Crawler\CurlCrawler->doCheck() ./vendor/sensiolabs/security-checker/SensioLabs/Security/Crawler/BaseCrawler.php:48
PHP  11. SensioLabs\Security\Crawler\CurlCrawler->getLockContents() ./vendor/sensiolabs/security-checker/SensioLabs/Security/Crawler/CurlCrawler.php:41
```

</details>

**Comment by cvuorinen** [comment]
I did a little digging and seems like this is what's causing the issue, the composer.lock file has `"packages-dev": null`.

Looks like some old composer version worked a little differently and when you executed composer update with the `--no-dev` flag it set the "packages-dev" key to null instead of empty array. The lock file in question is from September 2015, I tried with a newer composer and now it sets it to empty array even with the `--no-dev` flag. 

So, you can close the issue if you feel it's not necessary to fix it since it's working with latest composer. But should be easy enough to fix by casting to array or adding a null check (I can make a PR).

**Comment by fabpot** [comment]
@cvuorinen Can you confirm that 7d60f01 fixes the issue for you?

**Comment by cvuorinen** [comment]
@fabpot Yes, that fixed it.
