### ISSUE TITLE
integration with Jenkins

### ISSUE THREAD

**Issue by abdidarmawan007** [sensiolabs/security-checker#93]
can we integration with jenkins

for example my jenkins run this command, if we have bug/vulnerabilities jenkins alert build fail

php security-checker.phar security:check composer.lock

**Comment by theofidry** [comment]
You can already do this as it returns a status code

**Comment by fabpot** [comment]
As @theofidry has already mentioned, that's already possible. Feel free to reopen if you have something more specific in mind.
