### ISSUE TITLE
Self hosted solution ?

### ISSUE THREAD

**Issue by rockandska** [sensiolabs/security-checker#99]
Hi,
Is there any plan to let people self hosted your solution and be able to provide an alternative URI for the api endpoint ?
It could be an instance who mirror regularly the security-advisories repository and expose the same endpoints as the official API, or maybe just an instance who just receive the calls and forward them to the official endpoint ?

I had planned to totally isolate my ci runners from internet to be sure that nothing come from outside our infra but actually can't due to this limitation. I could install a squid-guard, install self-signed SSL cert on runners to be able to add some filter rules on SSL protocol but add complexity i don't want.

Thanks,
Best regards,

**Comment by rockandska** [comment]
The CLI seems already have an option to change the endpoint 
```
$ php security-checker.phar security:check --help | grep end-point
      --end-point=END-POINT  The security checker server URL

I've not seen any project on your organisation for this purpose

**Comment by fabpot** [comment]
Closing as there is no plan to do that.
